### ISSUE TITLE
conn.get_dict(key) leading to Cannot serialize '_io.BufferedReader' object

### ISSUE THREAD

**Issue by sandeepsingh0321** [vdloo/consul-kv#28]
Hi,
I am calling the "conn,get(key)" within a process triggered by python's pool.map under multiprocessing module and I keep getting following error:

`Traceback (most recent call last):
  File "heartbeat_trigger.py", line 195, in <module>
    main()
  File "heartbeat_trigger.py", line 145, in main
    result = pool.map(call_flow_driver, flow_group)
  File "C:\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x00000237D905F588>'. Reason: 'TypeError("cannot serialize '_io.BufferedReader' object")'
`
I don't get any error when I call the function without multiprocessing. Can someone suggest something ?

consul_kv: version: 0.7.3
python3: version: 3.7

**Comment by vdloo** [comment]
hi @sandeepsingh0321 this project is kind of abandoned. I don't think anybody is using it at this point in time, so if you want to fix this my suggestion would be to fork. Also I've never used or tested this on windows so maybe that has something to do with it.

**Comment by sandeepsingh0321** [comment]
sure @vdloo . I will try it out on UNIX and fork if something else works out.
In the meanwhile do you have suggestions on any other python library which is actively used to interact with consul?

**Comment by vdloo** [comment]
here is a list of alternatives https://www.consul.io/api/libraries-and-sdks.html

**Comment by sandeepsingh0321** [comment]
Thank you. I am closing this thread for now.
